[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "drf-inspector"
version = "0.1.3"
description = "A comprehensive Django app that provides visualization and analysis of your DRF backend."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.8"
license = { text = "MIT" }

authors = [
    { name = "UbaidUllah", email = "ubaidrao22388@gmail.com" }
]

urls = { Homepage = "https://github.com/codewithubaid1/drf-inspector" }

dependencies = [
    "Django>=3.2",
    "djangorestframework>=3.12"
]

classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 3.2",
    "Framework :: Django :: 4.0",
    "Framework :: Django :: 4.1",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.0",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content"
]

keywords = [
    "django",
    "djangorestframework",
    "drf",
    "api",
    "inspector",
    "visualizer",
    "architecture",
    "backend",
    "django-rest-framework",
    "drfvisualizer",
    "drf_inspector",
    "drf-visualizer"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]